### ISSUE TITLE
Calculate the checksum and expectedLength property.

### ISSUE THREAD

**Issue by arbazadam** [amake/dynamic-fonts-flutter#1]
```dart
import 'package:dynamic_fonts/dynamic_fonts.dart';
import 'package:flutter/material.dart';

class ExampleFont extends DynamicFontsFile {
  final DynamicFontsVariant variant;
  final String shopName;
  ExampleFont(this.variant, String expectedFileHash, int expectedLength,
      this.shopName)
      : super(expectedFileHash, expectedLength);

  String get _variant {
    switch (variant.fontWeight) {
      case FontWeight.bold:
        return 'Bold';
      default:
        return "Regular";
    }
  }

  @override
  String get url =>
      // 'https://raw.githubusercontent.com/bBoxType/FiraGO/9882ba0851f88ab904dc237f250db1d45641f45d/Fonts/FiraGO_TTF_1001/xzy/FiraGO-${variant.toApiFilenamePart()}.ttf';
      'https://test-bucket.s3.ap-central-1.amazon/test/fonts/$shopName/MagicTittle-$_variant.ttf';
}

```
//Registering the font

```dart
void _initCustomFonts() {
  DynamicFonts.register(
    'ExampleFont',
    [
      ExampleFont(
          const DynamicFontsVariant(
            fontWeight: FontWeight.normal,
            fontStyle: FontStyle.normal,
          ),
          //get the bytes and the hash.
          '495901c0c608ea265f4c31aa2a4c7a313e5cc2a3dd610da78a447fe8e07454a2',
          804888,
          'tcc'),
      ExampleFont(
          const DynamicFontsVariant(
            fontWeight: FontWeight.bold,
            fontStyle: FontStyle.normal,
          ),
          '36713ecac376845daa58738d2c2ba797cf6f6477b8c5bb4fa79721dc970e8081',
          813116,
          'tcc'),
    ].fold<Map<DynamicFontsVariant, DynamicFontsFile>>(
      {},
      (acc, file) => acc..[file.variant] = file,
    ),
  );
}

```
How can i calculate the hash and expectedLength property, as the files are inside a s3 bucket. Do i need to first read them and calculate the values? But in that case i am unaware of the exact file names which are gonna be picked from the bucket. I am very much confused as those are the required parameters.

**Comment by amake** [comment]
> Do i need to first read them and calculate the values?

Yes, you must provide the length and hash ahead of time in your application. Otherwise you can't be sure that what you downloaded was the expected file.

> But in that case i am unaware of the exact file names which are gonna be picked from the bucket

The exact file name picked from the bucket is that given by `DynamicFontsFile.url`.

**Comment by arbazadam** [comment]
Is there a way to add the dynamically loaded font to the fontFamily parameter of ThemeData?

eg:

```
ThemeData(fontFamily: DynamicFonts.getFont('ExampleFont').fontFamily);

```
Because when i just put the string to the font family as:

```
ThemeData(fontFamily: 'ExampleFont');

```
it takes the system default font instead of the dynamic font.

**Comment by amake** [comment]
That is difficult first of all because internally the font is loaded into the engine with a "mangled" name that combines the font family with the variant. The most reasonable way to access the mangled name is indeed `DynamicFonts.getFont('ExampleFont').fontFamily`.

Regarding the theme: I honestly don't understand the interactions between `Theme` and `DefaultTextStyle`.

I did some experimentation but I could not get a font family set via `ThemeData(fontFamily: 'ExampleFont')` to take effect on a `Text` widget. Instead I had to either supply a `TextStyle` to the `Text` widget directly, or use e.g. `DefaultTextStyle.merge(style: TextStyle(fontFamily: 'ExampleFont'))`.

**Comment by amake** [comment]
Actually I guess `ThemeData(fontFamily: 'ExampleFont')` will work if you set it in `MaterialApp`, and not lower in the tree as I was trying.

**Comment by alexrainman** [comment]
How do i handle font updates?

**Comment by amake** [comment]
> How do i handle font updates?

Can you be more specific?

If you want to supply an updated version of the font, then:

1. Deploy the new font files to your storage (S3 or whatever). Do *not* overwrite the old ones, as existing versions of your app will reject them due to the changed checksums/sizes.
2. Replace the existing checksums/sizes in your code.
3. Release a new version of your app.

**Comment by alexrainman** [comment]
What difference does it makes then if i need to release a new version of the app? There's nothing dynamic about it then.

**Comment by amake** [comment]
> What difference does it makes then if i need to release a new version of the app? There's nothing dynamic about it then.

"Dynamic" refers to allowing dynamic loading of fonts without statically bundling them with your app.

If you can suggest a better name and supply me with a time machine then I will be sure to correct it.
